services:
  backend:
    build: ./backend
    ports:
      - "18080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - quiz-net
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - quiz-net
networks:
  quiz-net:
    driver: bridge
